import React from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Arctic Well</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />      
      </Head>

      <div className={styles.text}>   
       <p>Now it's easy to stay</p> 
        </div>
        <div className={styles.text}> 
        <p>breezy!</p>
        </div>

        <div className={styles.button}>
        <button>Discover how it works!</button>
        </div>
    </div>
  );
}
