import Head from "next/head";
import Link from "next/link";
import styles from "../styles/More.module.css";
import Background from "../pages/background";
import React from "react";

export default function More() {
  <Head>
    <title>Arctic Well</title>
    <meta name="description" content="Generated by create next app" />
  </Head>;
  return (
    <div className={styles.more_div}>
      <Link href="/about">
        <h1 className={styles.more_links}>About us</h1>
      </Link>
      <hr className={styles.more_hr}></hr>
      <Link href="/boxes">
        <h1 className={styles.more_links}>Our boxes</h1>
      </Link>
      <hr className={styles.more_hr}></hr>
      <Link href="/rent">
        <h1 className={styles.more_links}>Rent-a-box</h1>
      </Link>
      <hr className={styles.more_hr}></hr>
      <Link href="/health">
        <h1 className={styles.more_links}>Health benefits</h1>
      </Link>
      <hr className={styles.more_hr}></hr>
      <Link href="/contact">
        <h1 className={styles.more_links}>Contact us</h1>
      </Link>
      <hr className={styles.more_hr}></hr>

      <p className={styles.more_footer}>Designed by Arctic Well in Sweden.</p>
      <Background />
    </div>
  );
}
