import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Background from "./background";

const More = () => {
  return (
    <div>
      <Head>
        <title>More</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background />
      <Banner />
      <div>
        <h1>About us</h1>
        <h1>FAQ</h1>
      </div>
    </div>
  );
};

export default More;
